### PR TITLE
Update to release 1.1

### PR DESCRIPTION
**Pull request by jkbonfield**
No code changes, just version numbering and docs.

### CODE REVIEW

**Comment by jmarshall** [comment]
You might also have a look at whatever patches Debian currently applies. See https://salsa.debian.org/med-team/htscodecs/-/tree/master/debian/patches — the only current one (as listed in _series_) is _link_with_libm_, which looks like it would be usefully applicable upstream.

**Comment by jkbonfield** [comment]
Good catch, and gah!  Why do they never feed back information upstream?

**Comment by jmarshall** [comment]
Why indeed… it's super frustrating :smile:

**Comment by jkbonfield** [comment]
I snuck in the `-lm` commit prior to the news/version update here, as otherwise it's needless red tape and extra shuffling / rebasing when making the release.  This PR can act as validation it works via the tests (which it does for me locally).

**Comment by daviesrob** [comment]
Updated with my improved distcheck fix.  The problem was that `tests/varint` was accidentally included in `EXTRA_DIST`, which caused make to attempt to build it earlier than it should have.

**Pull request merged**
