### PR TITLE
Make SIMD configure tests work for MacOS multiarch builds

### LINKED ISSUE #76: SIMD code selection and configury is incorrect for multi-arch compilation
[This investigation has occurred in a pysam context, which uses htslib's bundled-htscodecs build system rather than htscodecs's native build system. So this issue might equally properly be raised in htslib, but I expect any fix will span both htscodecs and htslib anyway.]

It seems that on modern macOS the usual way to build universal object files and executables is to compile and link with `-arch x86_64 -arch arm64`. This runs the compiler twice, once for each target, and then runs `lipo` to combine the two temporary _.o_ files into a single multi-arch (‘universal’) _.o_ file.

This does not interact well with htslib's _configure.ac_ SIMD probes (and presumably something similar happens with htscodecs's _configure.ac_):

```
# CFLAGS=[…] -arch arm64 -arch x86_64
[…]
checking whether C compiler accepts -mssse3 -mpopcnt -msse4.1... no
checking whether C compiler accepts -mavx2... no
checking whether C compiler accepts -mavx512f... no
checking whether C compiler supports ARM Neon... no
```

Looking in _config.log_ we see that the underlying x86_64 compilation has accepted `-mssse3` etc but the underlying arm64 compilation has produced errors, so the overall compilation fails too — resulting in `no`. And vice versa for the Neon probe.

This results in _rANS_static32x16pr_neon.o_ et al being omitted from the build, but the `*_neon()` invocations in _rANS_static4x16pr.c_ are included independent of the configure answer. This in turn leads to linking failure or for shared objects a failure to find `rans_compress_O0_32x16_neon` at runtime, as encountered in pysam-developers/pysam#1149.

It would be simple enough to fix the `*_neon()` invocation guard to respect the `no` answer and avoid this crash. However this pessimizes execution time for this multi-arch build by omitting all the SIMD implementations — really for this universal ARM/X86-64 build the answer to all four checks should be `yes`, with the 3 x86 SIMD implementations being used for the underlying x86_64 build and the Neon implementation being used for the underlying ARM build.

### PR DESCRIPTION
**Pull request by daviesrob**
Multiarch builds source files for each target, and then merges the results together into a single universal object file.  This causes issues with configure tests that attempt to detect architecture-specific features because if they fail on one architecture then they effectively fail for all of them.  In htscodecs this caused x86_64 SIMD code to be disabled when trying to build an x86_64 / arm64 universal binary because the related configure checks failed on the arm64 side - and likewise the arm NEON code was disabled due to a failing x86_64 test.

To fix:

- Add `#ifdef __x86_64__` and `#ifdef __ARM_NEON` to the source code so that architecture-specific code is filtered out at compile time.
- Add `#ifdef __x86_64__` guards to the x86 SIMD configure checks so that they don't fail for multiarch builds.
- Refactor the x86 SIMD tests so that instead of checking if a specific compiler option works, they find out if it is actually needed to build the code.  They do this by attempting to compile first without and then (if that fails) with the option.  The result will either be `none` (no option needed), `unsupported` (compilation failed both with and without the option), or an option that needs to be used to enable the feature.
- Remove the NEON configure test, and compile `rANS_static32x16pr_neon.c` unconditionally.
- Add dummy symbols to some source files to avoid "empty translation unit" errors if the code they contain has all been skipped due to `#ifdef` checks.

The combination of the `#ifdef __x86_64__` guards and revised configure checks means that when building for `x86_64`, including as part of a multiarch build, the flags will be enabled and disabled as needed; while on other platforms the test code will be skipped and the configure check will determine that no special compiler flags are needed.

Fixes #76

### CODE REVIEW

**Comment by jmarshall** [comment]
On the Intel side, what about `__i386__`?

**Comment by jkbonfield** [comment]
We did discuss this briefly, but concluded the only i386 machines with SIMD support are basically modern CPUs running in 32-bit mode.   The code should work fine in 32-bit mode, but it won't gain access to the accelerated implementations.  I don't really know how big an issue this is, and whether we actually care given it's a rather unusual scenario.

Do you have a better feeling for the reasoning behind using new CPUs in old modes?

**Comment by daviesrob** [comment]
I did think about adding `__i386__`, but then discovered that the accelerated code is [currently only called on x86_64](https://github.com/samtools/htscodecs/blob/cd0737fff5/htscodecs/rANS_static4x16pr.c#L829).  As James mentions, old CPUs won't have the accelerated instructions anyway so it was simpler to just use `__x86_64__` everywhere.

We could add `__i386__` if there's demand for it, but I think it would be best done as a separate project.

**Comment by jmarshall** [comment]
I had an idea the popcnt one would work on real i386, but perhaps not and perhaps the other requirements for that implementation would disable it on i386 anyway.

Debian still build for i386 so I was expecting they would notice the difference. However in the light of that guard on the dispatcher just being `__x86_64__`, never mind.

**Comment by jkbonfield** [comment]
Indeed, while popcnt itself may exist on older CPUs (I didn't check), we only use it in conjunction with a minimum of SSE4 I think.

I guess there is potential to use it elsewhere, but I'm not really minded to spend time optimising i386 :)

**Pull request merged**
